[package]
name = "password-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
argon2-kdf = "1.6.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
console = "0.15.11"
dialoguer = "0.11.0"
indicatif = "0.17.11"
